# EdgeFace-S (George et al. 2023)

_base_: base.yaml

model:
  name: edgeface_s

train:
  optimizer:
    type: adamw
    lr: 1.0e-3
    weight_decay: 0.05

  scheduler:
    type: cosine
    warmup_epochs: 2
